# -------------------------------
# 1. Base Image (build için)
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# 2. Proje dosyalarını kopyala
COPY *.sln .
COPY src/Services/ContactService/ContactService.Application/*.csproj src/Services/ContactService/ContactService.Application/
COPY src/Services/ContactService/ContactService.Infrastructure/*.csproj src/Services/ContactService/ContactService.Infrastructure/
COPY src/Services/ContactService/ContactService.Api/*.csproj src/Services/ContactService/ContactService.Api/
COPY src/Shared/Shared.BaseResponses/*.csproj src/Shared/Shared.BaseResponses/
COPY src/Shared/Shared.Events/*.csproj src/Shared/Shared.Events/

# 3. Projeleri restore et
RUN dotnet restore

# 4. Projeyi build et
COPY . .
WORKDIR /app/src/Services/ContactService/ContactService.Api
RUN dotnet publish -c Release -o /publish

# -------------------------------
# 5. Runtime Image (çalışma için)
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /publish .

# 6. Uygulama başlat
ENTRYPOINT ["dotnet", "ContactService.Api.dll"]